aleph-im/aleph-message

.dockerignore, aleph_message/__init__.py, aleph_message/models/__init__.py, aleph_message/models/abstract.py, aleph_message/models/program.py, aleph_message/tests/messages/machine.json, aleph_message/tests/test_models.py
This adds a new type of message to the Aleph specificiation: `PROGRAM`.
Aleph message types become therefore `POST`, `AGGREGATE`, `STORE` and `PROGRAM`.
A message of type program contains information about a program to be executed and it's execution environment.
The `type` field in the content of such message defines the kind of program and environment to use. At the moment, `vm-function` is the only type supported. It executes the program in a Virtual Machine in the spirit of a _cloud function_. The other fields of the content are specific to the type of message.
=> Feature: Add PROGRAM message specification

aleph_message/models/__init__.py, aleph_message/tests/test_models.py
Solution: Add optional field `forgotten_by`, but prevent it from having any value on FORGET messages using an extra validator.
=> Fix: Field `forgotten_by` was not supported by the Message models.

aleph_message/tests/test_types.py
Class names starting with "Test" have a special meaning for pytest.
=> Internal: fix test class name for ItemHash

aleph_message/tests/test_types.py
An exception should be raised when instanciating an ItemHash object directly.
Solution: Add tests to ensure that errors are raised when an invalid hash is passed.
=> Tests: Tests did not ensure invalid hashes errors

aleph_message/models/__init__.py, aleph_message/tests/test_types.py
Problems:
* Changes on ItemHash break using copy.copy(ItemHash(...)) (#22)
* Creating new ItemHash objects should not require passing an ItemType every time (#21)
Solution: compute the item type inside `__new__` instead of passing it as a parameter.
Resolves #20 and #21.
=> Fix: resolve breaking changes for ItemHash

aleph_message/models/__init__.py
Solution: Cache the result using `lru_cache` to avoir computing it too frequently.
=> Chore: ItemType was often computed with the same input

aleph_message/models/__init__.py
Problem: aggregates implement a key/value store, storing anything besides dictionaries makes no sense.
Solution: only accept dictionaries.
=> Fix: restrict aggregate content to dictionaries

aleph_message/models/__init__.py, aleph_message/models/item_hash.py, aleph_message/models/program.py
Problem: some users specify nonsensical strings in the ref field of programs and program volumes.
Solution: enforce the use of item hashes with the `ItemHash` type.
Moved the `ItemHash` and `ItemType` definitions to their own module to avoid circular imports.
=> Fix: restrict program refs to item hashes

aleph_message/models/__init__.py
Problem: Aleph messages coming from smart contracts do not have a signature.
Solution: allow None in the message signature field.
=> Fix: allow None in message signature field

aleph_message/status.py
The message status is used by APIs to represent the status of the processing of a message by a node.
=> Fix: Message status had no model representation.

aleph_message/models/program.py, aleph_message/utils.py
We want to reduce the confusion between the different units used for counting multiples of bytes.
This approach can help when using type validation.
=> Typing: Mebibytes missed specific typing

aleph_message/models/execution/instance.py, aleph_message/models/execution/volume.py, aleph_message/tests/messages/instance_machine.json
Problem: re-using the persistent volume model is not a perfect fit when implementing the logic to support instances in the rest of the aleph.im stack. Ex: the `mount` point does not make sense (it will always be `/`), neither do the `comment` or `name` fields. Similarly, the `parent` field must always be specified for root file systems.
Solution: use a custom model to refine the fields required.
=> Fix: use a dedicated model for instance rootfs

Dockerfile
Problem: some parts of the codebase are incompatible with Pydantic 2.0. We do not fix the version of Pydantic (and other dependencies) in the CI.
Solution: pip install the package directly in the CI Dockerfile.
=> Fix: CI was broken because of the release of Pydantic 2.0

aleph_message/models/__init__.py
Problem: Non-annotated class attributes are no longer supported by Pydantic.
Solution: add an annotation.
=> Fix: lib was not compatible with newer versions of Pydantic

aleph_message/models/__init__.py, aleph_message/models/base.py, aleph_message/models/execution/abstract.py, aleph_message/models/execution/base.py
In preparation for the Superfluid pay-as-you-go option for Programs/Instances.
=> Add `payment` field to `BaseExecutableContent` with specifics for payment type

aleph_message/models/__init__.py, aleph_message/models/execution/base.py, aleph_message/models/execution/instance.py, aleph_message/models/execution/program.py, aleph_message/tests/test_models.py
In reference to https://github.com/aleph-im/aleph-vm/issues/482.
Allows distinction between different types of plain code executions and more freedom in defining how it should be run.
=> Extend entrypoint parameter

aleph_message/models/__init__.py, aleph_message/models/execution/abstract.py, aleph_message/models/execution/program.py
To make the diffs for #90 and #89 simpler
=> Fix formatting with isort

setup.py
This made it impossible to install aleph-message together with fastapi
0.109.2
```
The conflict is caused by:
The user requested typing-extensions>=4.8.0
aleph-sdk-python 0.9.0 depends on typing-extensions
fastapi 0.109.2 depends on typing-extensions>=4.8.0
aleph-message 0.4.3 depends on typing-extensions~=4.5.0
```
Solution: Require version at least than instead of similar to.
=> Fix: Requirements were too strict

aleph_message/models/__init__.py
This caused issues from Mypy in the form `error: Module "aleph_message.models" does not explicitly export attribute "MessageType"  [attr-defined]`
Solution: Expose models that should be public.
=> Fix: Models were not exposed as public in `aleph_message.models`.

aleph_message/models/execution/environment.py
Fix: CPU features required for execution could not be specified.
This allows the user to specify CPU features the CPU that must be available in order to run the VM.
This should help with automatic and manual scheduling to the right machines.
@aliel , this should help for running CPU intensive software that takes advantage of avx2, fma, f16c :wink:
=> Add CPU features filter for executables

aleph_message/models/execution/base.py
Changing the condition to:
```python
self.type != PaymentType.hold
```
will allow us to add any new stream providers, other than superfluid, and still return "True"
=> Fix: is_stream to be compatible with any new stream providers

.github/dependabot.yml
Right now most of our dependencies are totally outdated, especially since we
pin all of them all the time and forget to check them after that.
This uses github dependabot built-in feature to do that.
Hopefully this will work with our usage of hatch.
You can see the related documentation here:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
And some blog post here:
https://github.blog/news-insights/product-news/keep-all-your-packages-up-to-date-with-dependabot/
If this works here, I'll migrate our other projects on this.
=> chore: configure dependabot to auto update dependencies

aleph_message/models/execution/instance.py, aleph_message/models/execution/volume.py, aleph_message/tests/test_models.py
Problem:
Instance Persistent Volume is currently limited to `100` GB, this value goes to `512` GB
=> Fix: max value of PersistentVolumeSizeMib to 512 GB

aleph_message/models/base.py
Implemented support for this new EVM chains:
```
ARBITRUM = "ARB"
BLAST = "BLAST"
BOB = "BOB"
CYBER = "CYBER"
FRAXTAL = "FRAX"
INK = "INK"
LINEA = "LINEA"
LISK = "LISK"
METIS = "METIS"
MODE = "MODE"
OPTIMISM = "OP"
POL = "POL"
WORLDCHAIN = "WLD"
ZORA = "ZORA"
```
=> Added new EVM chains

aleph_message/models/execution/environment.py, aleph_message/models/execution/instance.py, aleph_message/tests/messages/instance_content.json, aleph_message/tests/test_models.py
See [ALEPH-323](https://aleph-im.atlassian.net/browse/ALEPH-323?atlOrigin=eyJpIjoiYTM0MGI4ZmUxZjhkNGFlOWFmMjlhODc0NTY0ZjlkMDIiLCJwIjoiSmlyYS1Ob3Rpb25MaW5rLUludCJ9)
=> feat: allows CRN to publish a terms_and_condition

aleph_message/models/execution/instance.py, aleph_message/tests/test_models.py
Fix: Solved type saving issue, ensuring to get proper attributes on model validations.
=> Solve type saving issues
